"""添加health_data表和更新其他健康相关表

Revision ID: 38d51720d855
Revises: eb3c1711ed0a
Create Date: 2025-06-14 19:59:14.080241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d51720d855'
down_revision = 'eb3c1711ed0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
