"""create tables

Revision ID: a13a1321534d
Revises: None
Create Date: 2025-06-05 20:11:19.613375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13a1321534d'
down_revision = None  # 确保这里是 None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_bind().dialect.has_table(op.get_bind(), 'vector_store'):
        op.create_table('vector_store',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('content', sa.Text(), nullable=False),
            sa.Column('embedding', sa.Text(), nullable=False),
            sa.Column('source', sa.String(255), nullable=True),
            sa.Column('meta_info', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp')),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp')),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_store')
    # ### end Alembic commands ###
