"""添加health_data表的外键约束

Revision ID: a848d736bd9f
Revises: 38d51720d855
Create Date: 2025-06-14 20:15:41.581870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a848d736bd9f'
down_revision = '38d51720d855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
