"""update_sleep_record_datetime_fields

Revision ID: d2abe0592480
Revises: 211199aad207
Create Date: 2025-06-14 22:38:56.107318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2abe0592480'
down_revision = '211199aad207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
