"""cleanup_unused_tables

Revision ID: e84868cf6f21
Revises: a848d736bd9f
Create Date: 2025-06-14 20:44:37.899102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84868cf6f21'
down_revision = 'a848d736bd9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
